"""Creates AnimalCaretaker

Revision ID: 7af93e549b47
Revises: 32b84fcd8ac7
Create Date: 2023-05-15 14:52:48.617109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af93e549b47'
down_revision = '32b84fcd8ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_caretaker',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('caretaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['caretaker_id'], ['caretaker.id'], ),
    sa.PrimaryKeyConstraint('animal_id', 'caretaker_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_caretaker')
    # ### end Alembic commands ###
