"""Added new columns, age and species

Revision ID: ed9608d203a9
Revises: 46cc5d4a45a7
Create Date: 2023-05-03 10:26:45.397997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9608d203a9'
down_revision = '46cc5d4a45a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('species', sa.String(length=80), nullable=True))
    op.add_column('animal', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'age')
    op.drop_column('animal', 'species')
    # ### end Alembic commands ###
